---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: utils-evaluate
spec:
  params:
    - name: value
      default: 'true'
    - name: expected
      default: 'true'
  steps:
    env:
      - name: RESULT
        value: $(params.value)
      - name: EXPECTED_RESULT
        value: $(params.expected)
    image: ibmcom/pipeline-base-image:2.6
    script: |
        #!/usr/bin/env python3
        import os
        exit_code = 0
        if os.getenv("RESULT") != os.getenv("EXPECTED_RESULT"):
          print("RESULT '" + os.getenv("RESULT") + "' does not match '" + os.getenv("RESEXPECTED_RESULTULT") + "'")
          print("The actual result value did not match expected value.")
          exit_code = 1
        if exit_code == 0:
          print("Every Task result passed the check!")
        exit(exit_code)
