---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: doi-publish-buildrecord
spec:
  params:
    - name: app-name
      description: Logical application name for DevOps Insights
    - name: toolchain-id
      description: |
        Toolchain service instance id.
        Default to the toolchain containing the CD Tekton PipelineRun currently executed
      default: ""
    - name: build-number
      description: Devops Insights build number reference. Default to the CD Tekton Pipeline build number
      default: ""
    - name: build-status
      description: the build status (can be either pass | fail)
      default: "pass"
    - name: git-repository
      description: The url of the git repository
    - name: git-branch
      description: The repository branch on which the build has been performed
    - name: git-commit
      description: The git commit id
    - name: job-url
      description: The url to the job's build logs. Default to the CD Tekton PipelineRun currently executed
      default: ""
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: continuous-delivery-context-secret
      description: Name of the secret containing the continuous delivery pipeline context secrets
      default: "secure-properties"
    - name: toolchain-apikey-secret-key
      description: field in the secret that contains the api key used to access toolchain and DOI instance
      default: "toolchain-apikey"
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"
  results:
    - name: build-number
      description: Devops Insights build number reference used
  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)
  steps:
    - name: publish-build-record
      image: ibmcom/pipeline-base-image:2.6
      env:
        - name: IBM_CLOUD_API
          value: $(params.ibmcloud-api)
      script: |
        #!/bin/bash
        set -e -o pipefail

        if [ $PIPELINE_DEBUG == 1 ]; then
            pwd
            env
            trap env EXIT
            set -x
        fi
        echo "RUNNING"
      volumeMounts:
        - mountPath: /cd-config
          name: cd-config-volume
  volumes:
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
          - key: toolchain.json
            path: toolchain.json
